/**:
  ros__parameters:
    wide_neutral_angle_deg: 45.0
    steering_deadband_deg: 3.0
    qos:
      steering_input_sub:
        profile: sensor_data
        depth: 10
      mode_sub:
        profile: reliable
        depth: 10
      steering_command_pub:
        profile: reliable
        depth: 10
      steering_curvature_pub:
        profile: sensor_data
        depth: 10
